on:
  push:
    paths:
      - '.github/workflows/build-iso.yml'
  workflow_dispatch:

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

name: Release ISO
jobs:
  release-iso:
    name: Generate and Release ISOs
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        image_name: 
          - kandari
          - kandari-nvidia
        major_version:
          - 40
        image_tag:
          - latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine variant
        id: var
        run: |
          VARIANT="Kinoite"
          echo "variant=${VARIANT}" >> $GITHUB_ENV

      - name: Generate ISO  
        uses: jasonn3/build-container-installer@main
        id: build
        with:
          arch: x86_64
          image_name: ${{ matrix.image_name }}
          image_repo: ${{ env.IMAGE_REGISTRY }}
          variant: ${{ env.variant }}
          version: ${{ matrix.major_version }}
          image_tag: ${{ matrix.image_tag }}
          iso_name: ${{ matrix.image_name }}-${{ matrix.image_tag }}.iso
          web_ui: false
          enable_cache_dnf: "false"
          enable_cache_skopeo: "false"

      - name: Upload ISO + Checksum
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.build.outputs.iso_name }}
          path: |
            ${{ steps.build.outputs.iso_path }}
            ${{ steps.build.outputs.iso_path }}-CHECKSUM
          if-no-files-found: error
          retention-days: 1  # Change retention as needed

      - name: Generate Unique Tag
        id: tag
        run: |
          TAG_NAME=$(date +'%Y%m%d')
          echo "tag_name=${TAG_NAME}" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.tag_name }}
          release_name: Release ${{ env.tag_name }}
          body: |
            Release notes for ${{ env.tag_name }}
          draft: false
          prerelease: false

      - name: Upload ISO to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.build.outputs.iso_path }}
          asset_name: ${{ steps.build.outputs.iso_name }}
          asset_content_type: application/octet-stream

      - name: Upload Checksum to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.build.outputs.iso_path }}-CHECKSUM
          asset_name: ${{ steps.build.outputs.iso_name }}-CHECKSUM
          asset_content_type: text/plain
