on:
  push:
    paths:
      - '.github/workflows/build-iso.yml'
  workflow_dispatch:

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

name: Release ISO
jobs:
  release-iso:
    name: Generate and Release ISOs
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        image_name: 
          - kandari
          - kandari-nvidia
        major_version:
          - 40
        image_tag:
          - latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine variant
        id: var
        run: |
          VARIANT="Kinoite"
          echo "variant=${VARIANT}" >> $GITHUB_ENV

      - name: Generate ISO  
        uses: jasonn3/build-container-installer@main
        id: build
        with:
          arch: x86_64
          image_name: ${{ matrix.image_name }}
          image_repo: ${{ env.IMAGE_REGISTRY }}
          variant: ${{ env.variant }}
          version: ${{ matrix.major_version }}
          image_tag: ${{ matrix.image_tag }}
          iso_name: ${{ matrix.image_name }}-${{ matrix.image_tag }}.iso
          web_ui: false
          enable_cache_dnf: "false"
          enable_cache_skopeo: "false"

      - name: Upload ISO + Checksum
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.build.outputs.iso_name }}
          path: |
            ${{ steps.build.outputs.iso_path }}
            ${{ steps.build.outputs.iso_path }}-CHECKSUM
          if-no-files-found: error
          retention-days: 1  # Change retention as needed

      - name: Generate Unique Tag
        id: tag
        run: |
          TAG_NAME=$(date +'%Y%m%d')
          echo "tag_name=${TAG_NAME}" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: process.env.tag_name,
              name: process.env.tag_name,
              body: 'automated release',
              draft: false,
              prerelease: false
            });
            core.setOutput('upload_url', response.data.upload_url);

      - name: Upload ISO to GitHub Release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const isoPath = `${{ steps.build.outputs.iso_path }}`;
            const checksumPath = `${{ steps.build.outputs.iso_path }}-CHECKSUM`;

            const isoFile = fs.readFileSync(isoPath);
            const checksumFile = fs.readFileSync(checksumPath);

            await github.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: context.payload.release.id,
              name: ${{ steps.build.outputs.iso_name }},
              data: isoFile,
              headers: {
                'content-type': 'application/octet-stream',
                'content-length': isoFile.length
              }
            });

            await github.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: context.payload.release.id,
              name: `${{ steps.build.outputs.iso_name }}-CHECKSUM`,
              data: checksumFile,
              headers: {
                'content-type': 'text/plain',
                'content-length': checksumFile.length
              }
            });
